version: '3.8'

services:
    ui:
        container_name: plurish-ui
        image: plurish/ui
        build:
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - 80:8000
