version: '3.8'

services:
  reverse-proxy:
    container_name: plurish-reverse-proxy
    image: nginx:1.25.3-bookworm
    restart: always
    ports:
      - 8080:80
    volumes:
      - public-content:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  ui:
    container_name: plurish-ui
    image: plurish/ui:dev
    build:
      context: ./
      dockerfile: Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    volumes:
      - public-content:/var/www/public
      - /var/www/node_modules
      - /var/www/vendor
      - ./:/var/www

  db:
    image: mysql:8.1
    container_name: plurish-db-auth
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-auth:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-auth:
    name: plurish-db-auth

  public-content:
    name: public-static-content