controllers:
    resource:
        path: ../src/Http/Controller/
        namespace: App\Http\Controller
    type: attribute
    trailing_slash_on_root: false

api_controllers:
    resource:
        path: ../src/Http/Controller/Api/
        namespace: App\Http\Controller\Api
    type: attribute
    trailing_slash_on_root: false
    defaults:
        _format: json
